package graph

// このファイルはスキーマに基づいて自動生成されます。リゾルバの実装は
// 生成時にコピーされ、不明なコードはファイルの末尾に移動されます。
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"astro-graphql-todo/server-go/db"
	"astro-graphql-todo/server-go/graph/model"
	"context"
	"database/sql"
	"fmt"
	"strconv"
)

// mapDbTodoToModelTodo は、sqlcが生成したDBモデルをGraphQLのモデルに変換するヘルパー関数です。
func mapDbTodoToModelTodo(dbTodo db.Todo) *model.Todo {
	return &model.Todo{
		ID:        strconv.FormatInt(dbTodo.ID, 10),
		Text:      dbTodo.Text,
		Completed: dbTodo.Completed,
	}
}

// AddTodo は addTodo フィールドのリゾルバです。
func (r *mutationResolver) AddTodo(ctx context.Context, text string) (*model.Todo, error) {
	dbTodo, err := r.Queries.CreateTodo(ctx, db.CreateTodoParams{
		Text:      text,
		Completed: false,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create todo: %w", err)
	}
	return mapDbTodoToModelTodo(dbTodo), nil
}

// UpdateTodo は updateTodo フィールドのリゾルバです。
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, completed bool) (*model.Todo, error) {
	intID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid ID format: %w", err)
	}

	dbTodo, err := r.Queries.UpdateTodo(ctx, db.UpdateTodoParams{
		ID:        intID,
		Completed: completed,
	})
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("todo with id %s not found", id)
		}
		return nil, fmt.Errorf("failed to update todo: %w", err)
	}
	return mapDbTodoToModelTodo(dbTodo), nil
}

// DeleteTodo は deleteTodo フィールドのリゾルバです。
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (*bool, error) {
	intID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid ID format: %w", err)
	}

	err = r.Queries.DeleteTodo(ctx, intID)
	if err != nil {
		if err == sql.ErrNoRows {
			success := false
			return &success, nil // No row found to delete, so return false
		}
		return nil, fmt.Errorf("failed to delete todo: %w", err)
	}

	success := true // Deletion was successful
	return &success, nil
}

// Todos は todos フィールドのリゾルバです。
func (r *queryResolver) Todos(ctx context.Context, term *string) ([]*model.Todo, error) {
	var dbTodos []db.Todo
	var err error

	if term != nil && *term != "" {
		dbTodos, err = r.Queries.ListTodosByTerm(ctx, "%"+*term+"%")
	} else {
		dbTodos, err = r.Queries.ListTodos(ctx)
	}

	if err != nil {
		return nil, fmt.Errorf("failed to query todos: %w", err)
	}

	var todos []*model.Todo
	for _, dbTodo := range dbTodos {
		todos = append(todos, mapDbTodoToModelTodo(dbTodo))
	}

	return todos, nil
}

// Mutation は MutationResolver の実装を返します。
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query は QueryResolver の実装を返します。
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }